# Generated by Django 4.0.2 on 2022-02-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0004_remove_user_municipio_remove_user_provincia'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='municipio',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='provincia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
